### ISSUE TITLE
Identity Revocation Fails

### ISSUE THREAD

**Issue by goozang-records** [sunshine-protocol/sunshine-identity-ui#6]
When I revoke my identity, the confirmation screen asks me to confirm revoking shekohex@github instead of 4meta5@github . After I click confirm and it displays the Successful Revocation page, I go back to Identities and 4meta5 is still there.

**Comment by goozang-records** [comment]
Actually, it just took some time. It didn't work at first, but after some time, it did work. I'll have to put this in the directions.

**Comment by goozang-records** [comment]
Now the identity is no longer there, but I am having trouble re-proving it...Now it cannot find the posted gist.

**Comment by shekohex** [comment]
The problem was in the identity module and fixed recently, I published a new version and currently testing it.

**Comment by goozang-records** [comment]
succeeds now, nice job Shady 👏
